spring:
 datasource:
  url: jdbc:mysql://localhost:3306/notice?serverTimezone=UTC&characterEncoding=UTF-8
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver
   
 jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  show-sql: true
  hibernate:
   ddl-auto: create
  properties:
   hibernate:
    format_sql: true
  open-in-view: false
    
logging:
 level:
  root: info
  org.hibernate:
   SQL: DEBUG